# Sample .travis.yml file:
language: java

rvm: # the Ruby versions to be used
  - 3.4.0
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install ruby
  - gem install selenium-webdriver
  - sudo apt-get install junit
  - sudo apt-get install ant-optional
  - sudo apt-get install firefox
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
addons:
 firefox: '46.0'
    
    
#before_script:
 #  - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  # - Xvfb :1 -screen 0 1920x1080x24 &

script: 
- ant build
- ant Tests

 
