# Sample .travis.yml file:
language: java

rvm: # the Ruby versions to be used
  - 3.4.0
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install ruby
  - gem install selenium-webdriver
  - sudo apt-get install junit
  - sudo apt-get install ant-optional
  - sudo apt-get install firefox

addons:
 firefox: '46.0'
    
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
- ant build
- ant Tests

 
