# Sample .travis.yml file:
language: java

rvm: # the Ruby versions to be used
  - 3.4.0
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install ruby
  - gem install selenium-webdriver
  - sudo apt-get install junit
  - sudo apt-get install ant-optional
  - sudo apt-get install firefox

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script: 
- ant build
- ant Tests
