# Sample .travis.yml file:
language: java

rvm: # the Ruby versions to be used
  - 3.4.0
  
before_install:
  - rvm:
  - 2.2
  - jruby
  - sudo apt-get install ruby2.0
  - gem install selenium-webdriver
